//---------------------------------------------------
//
//	GBoot v0.0
//	NotArtyom
//	02/11/18
//
//---------------------------------------------------

	#include <stddef.h>
	#include <ctype.h>
	#include <sys/cdefs.h>

#define TYP_CNTRL 0x0001
#define TYP_SPACE 0x0002
#define TYP_BLANK 0x0004
#define TYP_PRINT 0x0008
#define TYP_PUNCT 0x0010
#define TYP_GRAPHIC 0x0020
#define TYP_DIGIT 0x0040
#define TYP_XDIGIT 0x0080
#define TYP_ALNUM 0x0100
#define TYP_UPPER 0x0200
#define TYP_LOWER 0x0400
#define TYP_ALPHA 0x0800

static const int type[128] = {
	TYP_CNTRL, // 00 NUL
	TYP_CNTRL, // 01 SOH
	TYP_CNTRL, // 02 STX
	TYP_CNTRL, // 03 ETX
	TYP_CNTRL, // 04 EOT
	TYP_CNTRL, // 05 ENQ
	TYP_CNTRL, // 06 ACK
	TYP_CNTRL, // 07 BEL
	TYP_CNTRL, // 08 BS
	TYP_CNTRL|TYP_BLANK|TYP_SPACE, // 09 HT
	TYP_CNTRL|TYP_SPACE, // 0A LF
	TYP_CNTRL|TYP_SPACE, // 0B VT
	TYP_CNTRL|TYP_SPACE, // 0C FF
	TYP_CNTRL|TYP_SPACE, // 0D CR
	TYP_CNTRL, // 0E SO
	TYP_CNTRL, // 0F SI
	TYP_CNTRL, // 10 DLE
	TYP_CNTRL, // 11 DC1
	TYP_CNTRL, // 12 DC2
	TYP_CNTRL, // 13 DC3
	TYP_CNTRL, // 14 DC4
	TYP_CNTRL, // 15 NAK
	TYP_CNTRL, // 16 SYN
	TYP_CNTRL, // 17 ETB
	TYP_CNTRL, // 18 CAN
	TYP_CNTRL, // 19 EM
	TYP_CNTRL, // 1A SUB
	TYP_CNTRL, // 1B ESC
	TYP_CNTRL, // 1C FS
	TYP_CNTRL, // 1D GS
	TYP_CNTRL, // 1E RS
	TYP_CNTRL, // 1F US
	TYP_BLANK|TYP_SPACE|TYP_PRINT, // 20 TYP_SPACE
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 21 !
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 22 "
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 23 #
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 24 $
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 25 %
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 26 &
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 27 '
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 28 (
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 29 )
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 2A *
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 2B +
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 2C ,
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 2D -
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 2E .
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 2F /
	TYP_DIGIT|TYP_XDIGIT|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 30 0
	TYP_DIGIT|TYP_XDIGIT|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 31 1
	TYP_DIGIT|TYP_XDIGIT|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 32 2
	TYP_DIGIT|TYP_XDIGIT|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 33 3
	TYP_DIGIT|TYP_XDIGIT|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 34 4
	TYP_DIGIT|TYP_XDIGIT|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 35 5
	TYP_DIGIT|TYP_XDIGIT|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 36 6
	TYP_DIGIT|TYP_XDIGIT|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 37 7
	TYP_DIGIT|TYP_XDIGIT|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 38 8
	TYP_DIGIT|TYP_XDIGIT|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 39 9
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 3A :
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 3B ;
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 3C <
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 3D =
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 3E >
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 3F ?
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 40 @
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_XDIGIT|TYP_GRAPHIC|TYP_PRINT, // 41 A
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_XDIGIT|TYP_GRAPHIC|TYP_PRINT, // 42 B
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_XDIGIT|TYP_GRAPHIC|TYP_PRINT, // 43 C
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_XDIGIT|TYP_GRAPHIC|TYP_PRINT, // 44 D
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_XDIGIT|TYP_GRAPHIC|TYP_PRINT, // 45 E
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_XDIGIT|TYP_GRAPHIC|TYP_PRINT, // 46 F
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 47 G
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 48 H
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 49 I
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 4A J
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 4B K
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 4C L
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 4D M
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 4E N
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 4F O
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 50 P
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 51 Q
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 52 R
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 53 S
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 54 T
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 55 U
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 56 V
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 57 W
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 58 X
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 59 Y
	TYP_UPPER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 5A Z
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 5B [
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 5C '\'
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 5D ]
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 5E ^
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 5F _
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 60 `
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_XDIGIT|TYP_GRAPHIC|TYP_PRINT, // 61 a
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_XDIGIT|TYP_GRAPHIC|TYP_PRINT, // 62 b
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_XDIGIT|TYP_GRAPHIC|TYP_PRINT, // 63 c
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_XDIGIT|TYP_GRAPHIC|TYP_PRINT, // 64 d
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_XDIGIT|TYP_GRAPHIC|TYP_PRINT, // 65 e
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_XDIGIT|TYP_GRAPHIC|TYP_PRINT, // 66 f
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 67 g
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 68 h
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 69 i
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 6A j
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 6B k
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 6C l
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 6D m
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 6E n
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 6F o
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 70 p
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 71 q
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 72 r
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 73 s
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 74 t
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 75 u
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 76 v
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 77 w
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 78 x
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 79 y
	TYP_LOWER|TYP_ALPHA|TYP_ALNUM|TYP_GRAPHIC|TYP_PRINT, // 7A z
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 7B {
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 7C |
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 7D }
	TYP_PUNCT|TYP_GRAPHIC|TYP_PRINT, // 7E ~
	TYP_CNTRL // 7F DEL
};

#define ASCII(x) (x >= 0 && x <= 0x7F)

__weak_symbol int isalnum(int ch) {
	return ASCII(ch)? (type[ch] & TYP_ALNUM): 0;
}
__weak_symbol int isalpha(int ch) { return ASCII(ch)? (type[ch] & TYP_ALPHA): 0; }
__weak_symbol int isblank(int ch) { return ASCII(ch)? (type[ch] & TYP_BLANK): 0; }
__weak_symbol int iscntrl(int ch) { return ASCII(ch)? (type[ch] & TYP_CNTRL): 0; }
__weak_symbol int isdigit(int ch) { return ASCII(ch)? (type[ch] & TYP_DIGIT): 0; }
__weak_symbol int isgraph(int ch) { return ASCII(ch)? (type[ch] & TYP_GRAPHIC): 0; }
__weak_symbol int islower(int ch) { return ASCII(ch)? (type[ch] & TYP_LOWER): 0; }
__weak_symbol int isprint(int ch) { return ASCII(ch)? (type[ch] & TYP_PRINT): 0; }
__weak_symbol int ispunct(int ch) { return ASCII(ch)? (type[ch] & TYP_PUNCT): 0; }
__weak_symbol int isspace(int ch) { return ASCII(ch)? (type[ch] & TYP_SPACE): 0; }
__weak_symbol int isupper(int ch) { return ASCII(ch)? (type[ch] & TYP_UPPER): 0; }
__weak_symbol int isxdigit(int ch) { return ASCII(ch)? (type[ch] & TYP_XDIGIT): 0; }

__weak_symbol int tolower(int ch) { return isupper(ch)? (ch + 'a' - 'A'): ch; }
__weak_symbol int toupper(int ch) { return islower(ch)? (ch + 'A' - 'a'): ch; }
